// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bars3IconOutline: typeof import('@heroicons/vue/24/outline/esm/Bars3Icon.js')['default']
    ChevronDownIconOutline: typeof import('@heroicons/vue/24/outline/esm/ChevronDownIcon.js')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
