export const safelist = [
  'vc-container',
  'vc-monthly',
  'vc-purple',
  'vc-light',
  'vc-bordered',
  'vc-pane-container',
  'vc-pane-header-wrapper',
  'vc-header, is-lg',
  'vc-arrow', 'vc-prev', 'vc-focus',
  'vc-base-icon',
  'vc-next',
  'vc-pane-layout',
  'vc-pane', 'row-1', 'row-from-end-1', 'column-1', 'column-from-end-1',
  'vc-title',
  'vc-weeks',
  'vc-weekdays', 'vc-week',
  'vc-weekday', 'vc-weekday-1', 'vc-weekday-2', 'vc-weekday-3', 'vc-weekday-4', 'vc-weekday-5', 'vc-weekday-6', 'vc-weekday-7',
  'vc-day', 'id-2023-05-01', 'day-1', 'day-from-end-31', 'weekday-2', 'weekday-position-1', 'weekday-ordinal-1', 'weekday-ordinal-from-end-5', 'week-1', 'week-from-end-5', 'is-first-day', 'in-month', 'on-top', 'on-left', 'vc-day-box-center-center',
]
